export default {
  SET_MENUS: 'SET_MENUS',
  SET_ORIGIN_MENUS: 'SET_ORIGIN_MENUS',
  // SET_NAV: 'SET_NAV',
  SET_ACTIVE_MENU: 'SET_ACTIVE_MENU',
  SET_BG: 'SET_BG',
  // 设置主题
  SET_THEME: 'SET_THEME',
  SET_THEME_COLORS: 'SET_THEME_COLORS',
  SET_TITLE: 'SET_TITLE',
  SET_COUNT: 'SET_COUNT',
  SET_WORKSPACEhEIGHT: 'SET_WORKSPACEhEIGHT',
  SET_RATIO: 'SET_RATIO'
}
